services:
  app:
    image: abdulaziz111/market:tag2
    build:
      context: .
    container_name: market
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres_data:
