services:
  # server:
  #   build:
  #     context: .
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5433:5432'
    networks:
      - postgres

  redis:
    image: redis
    ports:
      - '6379:6379'
    
networks:
  postgres: 
    driver: bridge
